# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sGR1zOSX65_WU2S8luZGbiGQAjmOiJGN
"""

try:
    import streamlit as st
except ModuleNotFoundError:
    import os
    os.system("pip install streamlit")
    import streamlit as st

import pandas as pd
import plotly.express as px

df=pd.read_csv('/content/Advertising_F.csv')
df.head()

#show admin stuff
st.title("Advertising Effectiveness Dashboard_Eileena")
st.sidebar.header("Filters")
x_var=st.sidebar.selectbox("x-axis", ['TV','radio','newspaper'])
y_var=st.sidebar.selectbox("y-axis",['sales'])
#show a scatter plot
fig=px.scatter(df,x=x_var,y=y_var,trendline='ols')
st.plotly_chart(fig)
#show the data frame
st.write('### Data Frame')
st.dataframe(df)

#lets show a map
st.title("I'm the Map!!!!")
fig=px.scatter_mapbox(df,lat='latitude',lon='longitude',color='sales',
                      size='TV',hover_name='City')
fig.update_layout(mapbox_style='carto-positron')
st.plotly_chart(fig)